/*******************************************************************************
 * Copyright (c) 2008-2019 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.provider;

import de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.util.PropertyinstancesAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemFontProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PropertyinstancesItemProviderAdapterFactory extends PropertyinstancesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PropertyinstancesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemFontProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ValuePropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValuePropertyInstanceItemProvider valuePropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ValuePropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValuePropertyInstanceAdapter() {
		if (valuePropertyInstanceItemProvider == null) {
			valuePropertyInstanceItemProvider = new ValuePropertyInstanceItemProvider(this);
		}

		return valuePropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.UnitValuePropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitValuePropertyInstanceItemProvider unitValuePropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.UnitValuePropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitValuePropertyInstanceAdapter() {
		if (unitValuePropertyInstanceItemProvider == null) {
			unitValuePropertyInstanceItemProvider = new UnitValuePropertyInstanceItemProvider(this);
		}

		return unitValuePropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ReferencePropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferencePropertyInstanceItemProvider referencePropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ReferencePropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferencePropertyInstanceAdapter() {
		if (referencePropertyInstanceItemProvider == null) {
			referencePropertyInstanceItemProvider = new ReferencePropertyInstanceItemProvider(this);
		}

		return referencePropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.EReferencePropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EReferencePropertyInstanceItemProvider eReferencePropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.EReferencePropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEReferencePropertyInstanceAdapter() {
		if (eReferencePropertyInstanceItemProvider == null) {
			eReferencePropertyInstanceItemProvider = new EReferencePropertyInstanceItemProvider(this);
		}

		return eReferencePropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ComposedPropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedPropertyInstanceItemProvider composedPropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ComposedPropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComposedPropertyInstanceAdapter() {
		if (composedPropertyInstanceItemProvider == null) {
			composedPropertyInstanceItemProvider = new ComposedPropertyInstanceItemProvider(this);
		}

		return composedPropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ArrayInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayInstanceItemProvider arrayInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ArrayInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayInstanceAdapter() {
		if (arrayInstanceItemProvider == null) {
			arrayInstanceItemProvider = new ArrayInstanceItemProvider(this);
		}

		return arrayInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ResourcePropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourcePropertyInstanceItemProvider resourcePropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.ResourcePropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourcePropertyInstanceAdapter() {
		if (resourcePropertyInstanceItemProvider == null) {
			resourcePropertyInstanceItemProvider = new ResourcePropertyInstanceItemProvider(this);
		}

		return resourcePropertyInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.EnumUnitPropertyInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumUnitPropertyInstanceItemProvider enumUnitPropertyInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.dlr.sc.virsat.model.dvlm.categories.propertyinstances.EnumUnitPropertyInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumUnitPropertyInstanceAdapter() {
		if (enumUnitPropertyInstanceItemProvider == null) {
			enumUnitPropertyInstanceItemProvider = new EnumUnitPropertyInstanceItemProvider(this);
		}

		return enumUnitPropertyInstanceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (valuePropertyInstanceItemProvider != null) valuePropertyInstanceItemProvider.dispose();
		if (unitValuePropertyInstanceItemProvider != null) unitValuePropertyInstanceItemProvider.dispose();
		if (referencePropertyInstanceItemProvider != null) referencePropertyInstanceItemProvider.dispose();
		if (eReferencePropertyInstanceItemProvider != null) eReferencePropertyInstanceItemProvider.dispose();
		if (composedPropertyInstanceItemProvider != null) composedPropertyInstanceItemProvider.dispose();
		if (arrayInstanceItemProvider != null) arrayInstanceItemProvider.dispose();
		if (resourcePropertyInstanceItemProvider != null) resourcePropertyInstanceItemProvider.dispose();
		if (enumUnitPropertyInstanceItemProvider != null) enumUnitPropertyInstanceItemProvider.dispose();
	}

}
