/*******************************************************************************
 * Copyright (c) 2008-2019 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package de.dlr.sc.virsat.uieingine.ui;

import org.eclipse.emf.common.EMFPlugin;
import org.eclipse.emf.common.ui.EclipseUIPlugin;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.jface.resource.ImageRegistry;

/**
 * Activator plugin for the UIEngine
 * 
 * This class has originally been generated by the EMF Model but has been manually modified!
 * 
 * @author muel_s8
 *
 */
public final class DVLMEditorPlugin extends EMFPlugin {
	
	public static final String IMAGE_CALCULATED = "Image_VirSat_Calculated";

	public static final DVLMEditorPlugin INSTANCE = new DVLMEditorPlugin();
	
	public static final String ID = "de.dlr.sc.virsat.uiengine.ui";

	private static Implementation plugin;

	/**
	 * Default constructor
	 */
	public DVLMEditorPlugin() {
		super(new ResourceLocator [] {
			});
	}

	@Override
	public ResourceLocator getPluginResourceLocator() {
		return plugin;
	}
	
	/**
	 * Gets the singleton instance of this plugin
	 * @return the ui activator
	 */
	public static Implementation getPlugin() {
		return plugin;
	}
	
	/**
	 * Actual internal implementation as a UI plugin
	 * @author muel_s8
	 *
	 */
	public static class Implementation extends EclipseUIPlugin {
		/**
		 * Default constructor
		 */
		public Implementation() {
			super();
			plugin = this;
		}
		
		@Override
		protected void initializeImageRegistry(ImageRegistry reg) {
			super.initializeImageRegistry(reg);
			reg.put(IMAGE_CALCULATED, getImageDescriptor("resources/icons/VirSat_Calculated.gif"));
		}
		
		/**
		 * Method that directly hands back an image descriptor from the current Bundle resources
		 * @param path The path to the resource 
		 * @return the according ImageDescriptor
		 */
		public static ImageDescriptor getImageDescriptor(String path) {
			return imageDescriptorFromPlugin(ID, path);
		}
	}

}
