/**
 * generated by Xtext
 */
package de.dlr.sc.virsat.model.calculation.validation;

import de.dlr.sc.virsat.model.calculation.validation.AbstractEquationDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EquationDSLValidator extends AbstractEquationDSLValidator {
}
